name: Branch Link Check

on:
  workflow_dispatch:
  schedule:
    - cron: "00 11 * * *" # run at 16:30 PM IST

jobs:
  paradox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: branch-1.0.x
      - uses: coursier/setup-action@v1.2.0
        with:
          jvm: temurin:1.21
      - uses: coursier/cache-action@v6

      - name: Paradox Validate Links
        run: sbtn paradoxValidateLinks

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-linkcheck
